"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from .asset import Asset
from .state import ConnectionState
from .types.user import Collectible as CollectiblePayload

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
__all__ = ('Collectible', )
class Collectible:
    """Represents a user's collectible.

    .. versionadded:: 2.7

    Attributes
    ----------
    label: :class:`str`
        The label of the collectible.
    palette: Optional[:class:`NameplatePalette`]
        The palette of the collectible.
        This is only available if ``type`` is
        :class:`CollectibleType.nameplate`.
    sku_id: :class:`int`
        The SKU ID of the collectible.
    type: :class:`CollectibleType`
        The type of the collectible.
    expires_at: Optional[:class:`datetime.datetime`]
        The expiration date of the collectible. If applicable.
    """
    __slots__ = ...
    def __init__(self, *, state: ConnectionState, type: str, data: CollectiblePayload) -> None:
        ...
    
    @property
    def static(self) -> Asset:
        """:class:`Asset`: The static asset of the collectible."""
        ...
    
    @property
    def animated(self) -> Asset:
        """:class:`Asset`: The animated asset of the collectible."""
        ...
    
    def __repr__(self) -> str:
        ...
    


