"""
This type stub file was generated by pyright.
"""

from typing import ClassVar, Literal, Optional, TYPE_CHECKING, Tuple, Union
from .asset import AssetMixin
from .enums import ComponentType, SelectDefaultValueType
from .flags import AttachmentFlags
from .colour import Colour
from .file import File
from .partial_emoji import PartialEmoji
from typing_extensions import Self
from .types.components import ActionRow as ActionRowPayload, ButtonComponent as ButtonComponentPayload, CheckboxComponent as CheckboxComponentPayload, CheckboxGroupComponent as CheckboxGroupComponentPayload, CheckboxGroupOption as CheckboxGroupOptionPayload, Component as ComponentPayload, ContainerComponent as ContainerComponentPayload, FileComponent as FileComponentPayload, FileUploadComponent as FileUploadComponentPayload, LabelComponent as LabelComponentPayload, MediaGalleryComponent as MediaGalleryComponentPayload, MediaGalleryItem as MediaGalleryItemPayload, RadioGroupComponent as RadioGroupComponentPayload, RadioGroupOption as RadioGroupOptionPayload, SectionComponent as SectionComponentPayload, SelectDefaultValues as SelectDefaultValuesPayload, SelectMenu as SelectMenuPayload, SelectOption as SelectOptionPayload, SeparatorComponent as SeparatorComponentPayload, TextComponent as TextComponentPayload, TextInput as TextInputPayload, ThumbnailComponent as ThumbnailComponentPayload
from .emoji import Emoji
from .abc import Snowflake
from .state import ConnectionState

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ActionRowChildComponentType = Union['Button', 'SelectMenu', 'TextInput']
    SectionComponentType = Union['TextDisplay']
    MessageComponentType = Union[ActionRowChildComponentType, SectionComponentType, 'ActionRow', 'SectionComponent', 'ThumbnailComponent', 'MediaGalleryComponent', 'FileComponent', 'SectionComponent', 'Component',]
    OptionPayload = Union[SelectOptionPayload, RadioGroupOptionPayload, CheckboxGroupOptionPayload]
__all__ = ('Component', 'ActionRow', 'Button', 'SelectMenu', 'SelectOption', 'TextInput', 'SelectDefaultValue', 'SectionComponent', 'ThumbnailComponent', 'UnfurledMediaItem', 'MediaGalleryItem', 'MediaGalleryComponent', 'FileComponent', 'SectionComponent', 'Container', 'TextDisplay', 'SeparatorComponent', 'LabelComponent', 'FileUploadComponent', 'RadioGroupComponent', 'CheckboxGroupComponent', 'CheckboxComponent', 'RadioGroupOption', 'CheckboxGroupOption')
class Component:
    """Represents a Discord Bot UI Kit Component.

    The components supported by Discord are:

    - :class:`ActionRow`
    - :class:`Button`
    - :class:`SelectMenu`
    - :class:`TextInput`
    - :class:`SectionComponent`
    - :class:`TextDisplay`
    - :class:`ThumbnailComponent`
    - :class:`MediaGalleryComponent`
    - :class:`FileComponent`
    - :class:`SeparatorComponent`
    - :class:`Container`
    - :class:`LabelComponent`
    - :class:`FileUploadComponent`

    This class is abstract and cannot be instantiated.

    .. versionadded:: 2.0
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]]
    def __repr__(self) -> str:
        ...
    
    @property
    def type(self) -> ComponentType:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> ComponentPayload:
        ...
    


class BaseOption:
    """Represents a base option for components that have options.

    This currently implements:

    - :class:`SelectOption`
    - :class:`RadioGroupOption`
    - :class:`CheckboxGroupOption`

    .. versionadded:: 2.7
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, *, label: str, value: str = ..., description: Optional[str] = ..., default: bool = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    @classmethod
    def from_dict(cls, data: OptionPayload) -> Self:
        ...
    
    def to_dict(self) -> OptionPayload:
        ...
    
    def copy(self) -> Self:
        ...
    


class ActionRow(Component):
    """Represents a Discord Bot UI Kit Action Row.

    This is a component that holds up to 5 children components in a row.

    This inherits from :class:`Component`.

    .. versionadded:: 2.0

    Attributes
    ------------
    children: List[Union[:class:`Button`, :class:`SelectMenu`, :class:`TextInput`]]
        The children components that this holds, if any.
    id: Optional[:class:`int`]
        The ID of this component.

        .. versionadded:: 2.6
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: ActionRowPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.action_row]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> ActionRowPayload:
        ...
    


class Button(Component):
    """Represents a button from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type to create a button is :class:`discord.ui.Button`
        not this one.

    .. versionadded:: 2.0

    Attributes
    -----------
    style: :class:`.ButtonStyle`
        The style of the button.
    custom_id: Optional[:class:`str`]
        The ID of the button that gets received during an interaction.
        If this button is for a URL, it does not have a custom ID.
    url: Optional[:class:`str`]
        The URL this button sends you to.
    disabled: :class:`bool`
        Whether the button is disabled or not.
    label: Optional[:class:`str`]
        The label of the button, if any.
    emoji: Optional[:class:`PartialEmoji`]
        The emoji of the button, if available.
    sku_id: Optional[:class:`int`]
        The SKU ID this button sends you to, if available.

        .. versionadded:: 2.4
    id: Optional[:class:`int`]
        The ID of this component.

        .. versionadded:: 2.6
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: ButtonComponentPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.button]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> ButtonComponentPayload:
        ...
    


class SelectMenu(Component):
    """Represents a select menu from the Discord Bot UI Kit.

    A select menu is functionally the same as a dropdown, however
    on mobile it renders a bit differently.

    .. note::

        The user constructible and usable type to create a select menu is
        :class:`discord.ui.Select` not this one.

    .. versionadded:: 2.0

    Attributes
    ------------
    type: :class:`ComponentType`
        The type of component.
    custom_id: Optional[:class:`str`]
        The ID of the select menu that gets received during an interaction.
    placeholder: Optional[:class:`str`]
        The placeholder text that is shown if nothing is selected, if any.
    min_values: :class:`int`
        The minimum number of items that must be chosen for this select menu.
        Defaults to 1 and must be between 0 and 25.
    max_values: :class:`int`
        The maximum number of items that must be chosen for this select menu.
        Defaults to 1 and must be between 1 and 25.
    options: List[:class:`SelectOption`]
        A list of options that can be selected in this menu.
    disabled: :class:`bool`
        Whether the select is disabled or not.
    channel_types: List[:class:`.ChannelType`]
        A list of channel types that are allowed to be chosen in this select menu.
    id: Optional[:class:`int`]
        The ID of this component.

        .. versionadded:: 2.6
    required: :class:`bool`
        Whether the select is required. Only applicable within modals.

        .. versionadded:: 2.6
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: SelectMenuPayload, /) -> None:
        ...
    
    def to_dict(self) -> SelectMenuPayload:
        ...
    


class SelectOption(BaseOption):
    """Represents a select menu's option.

    These can be created by users.

    .. versionadded:: 2.0

    Parameters
    -----------
    label: :class:`str`
        The label of the option. This is displayed to users.
        Can only be up to 100 characters.
    value: :class:`str`
        The value of the option. This is not displayed to users.
        If not provided when constructed then it defaults to the label.
        Can only be up to 100 characters.
    description: Optional[:class:`str`]
        An additional description of the option, if any.
        Can only be up to 100 characters.
    emoji: Optional[Union[:class:`str`, :class:`Emoji`, :class:`PartialEmoji`]]
        The emoji of the option, if available.
    default: :class:`bool`
        Whether this option is selected by default.

    Attributes
    -----------
    label: :class:`str`
        The label of the option. This is displayed to users.
    value: :class:`str`
        The value of the option. This is not displayed to users.
        If not provided when constructed then it defaults to the
        label.
    description: Optional[:class:`str`]
        An additional description of the option, if any.
    default: :class:`bool`
        Whether this option is selected by default.
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__ = ...
    def __init__(self, *, label: str, value: str = ..., description: Optional[str] = ..., emoji: Optional[Union[str, Emoji, PartialEmoji]] = ..., default: bool = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def emoji(self) -> Optional[PartialEmoji]:
        """Optional[:class:`.PartialEmoji`]: The emoji of the option, if available."""
        ...
    
    @emoji.setter
    def emoji(self, value: Optional[Union[str, Emoji, PartialEmoji]]) -> None:
        ...
    
    @classmethod
    def from_dict(cls, data: SelectOptionPayload) -> Self:
        ...
    
    def to_dict(self) -> SelectOptionPayload:
        ...
    


class TextInput(Component):
    """Represents a text input from the Discord Bot UI Kit.

    .. note::
        The user constructible and usable type to create a text input is
        :class:`discord.ui.TextInput` not this one.

    .. versionadded:: 2.0

    Attributes
    ------------
    custom_id: Optional[:class:`str`]
        The ID of the text input that gets received during an interaction.
    label: Optional[:class:`str`]
        The label to display above the text input.
    style: :class:`TextStyle`
        The style of the text input.
    placeholder: Optional[:class:`str`]
        The placeholder text to display when the text input is empty.
    value: Optional[:class:`str`]
        The default value of the text input.
    required: :class:`bool`
        Whether the text input is required.
    min_length: Optional[:class:`int`]
        The minimum length of the text input.
    max_length: Optional[:class:`int`]
        The maximum length of the text input.
    id: Optional[:class:`int`]
        The ID of this component.

        .. versionadded:: 2.6
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: TextInputPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.text_input]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> TextInputPayload:
        ...
    
    @property
    def default(self) -> Optional[str]:
        """Optional[:class:`str`]: The default value of the text input.

        This is an alias to :attr:`value`.
        """
        ...
    


class SelectDefaultValue:
    """Represents a select menu's default value.

    These can be created by users.

    .. versionadded:: 2.4

    Parameters
    -----------
    id: :class:`int`
        The id of a role, user, or channel.
    type: :class:`SelectDefaultValueType`
        The type of value that ``id`` represents.
    """
    def __init__(self, *, id: int, type: SelectDefaultValueType) -> None:
        ...
    
    @property
    def type(self) -> SelectDefaultValueType:
        """:class:`SelectDefaultValueType`: The type of value that ``id`` represents."""
        ...
    
    @type.setter
    def type(self, value: SelectDefaultValueType) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @classmethod
    def from_dict(cls, data: SelectDefaultValuesPayload) -> SelectDefaultValue:
        ...
    
    def to_dict(self) -> SelectDefaultValuesPayload:
        ...
    
    @classmethod
    def from_channel(cls, channel: Snowflake, /) -> Self:
        """Creates a :class:`SelectDefaultValue` with the type set to :attr:`~SelectDefaultValueType.channel`.

        Parameters
        -----------
        channel: :class:`~discord.abc.Snowflake`
            The channel to create the default value for.

        Returns
        --------
        :class:`SelectDefaultValue`
            The default value created with the channel.
        """
        ...
    
    @classmethod
    def from_role(cls, role: Snowflake, /) -> Self:
        """Creates a :class:`SelectDefaultValue` with the type set to :attr:`~SelectDefaultValueType.role`.

        Parameters
        -----------
        role: :class:`~discord.abc.Snowflake`
            The role to create the default value for.

        Returns
        --------
        :class:`SelectDefaultValue`
            The default value created with the role.
        """
        ...
    
    @classmethod
    def from_user(cls, user: Snowflake, /) -> Self:
        """Creates a :class:`SelectDefaultValue` with the type set to :attr:`~SelectDefaultValueType.user`.

        Parameters
        -----------
        user: :class:`~discord.abc.Snowflake`
            The user to create the default value for.

        Returns
        --------
        :class:`SelectDefaultValue`
            The default value created with the user.
        """
        ...
    


class SectionComponent(Component):
    """Represents a section from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type to create a section is :class:`discord.ui.Section`
        not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    children: List[:class:`TextDisplay`]
        The components on this section.
    accessory: :class:`Component`
        The section accessory.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: SectionComponentPayload, state: Optional[ConnectionState]) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.section]:
        ...
    
    def to_dict(self) -> SectionComponentPayload:
        ...
    


class ThumbnailComponent(Component):
    """Represents a Thumbnail from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type to create a thumbnail is :class:`discord.ui.Thumbnail`
        not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    media: :class:`UnfurledMediaItem`
        The media for this thumbnail.
    description: Optional[:class:`str`]
        The description shown within this thumbnail.
    spoiler: :class:`bool`
        Whether this thumbnail is flagged as a spoiler.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: ThumbnailComponentPayload, state: Optional[ConnectionState]) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.thumbnail]:
        ...
    
    def to_dict(self) -> ThumbnailComponentPayload:
        ...
    


class TextDisplay(Component):
    """Represents a text display from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type to create a text display is
        :class:`discord.ui.TextDisplay` not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    content: :class:`str`
        The content that this display shows.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: TextComponentPayload) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.text_display]:
        ...
    
    def to_dict(self) -> TextComponentPayload:
        ...
    


class UnfurledMediaItem(AssetMixin):
    """Represents an unfurled media item.

    .. versionadded:: 2.6

    Parameters
    ----------
    url: :class:`str`
        The URL of this media item. This can be an arbitrary url or a reference to a local
        file uploaded as an attachment within the message, which can be accessed with the
        ``attachment://<filename>`` format.

    Attributes
    ----------
    url: :class:`str`
        The URL of this media item.
    proxy_url: Optional[:class:`str`]
        The proxy URL. This is a cached version of the :attr:`.url` in the
        case of images. When the message is deleted, this URL might be valid for a few minutes
        or not valid at all.
    height: Optional[:class:`int`]
        The media item's height, in pixels. Only applicable to images and videos.
    width: Optional[:class:`int`]
        The media item's width, in pixels. Only applicable to images and videos.
    content_type: Optional[:class:`str`]
        The media item's `media type <https://en.wikipedia.org/wiki/Media_type>`_
    placeholder: Optional[:class:`str`]
        The media item's placeholder.
    loading_state: Optional[:class:`MediaItemLoadingState`]
        The loading state of this media item.
    attachment_id: Optional[:class:`int`]
        The attachment id this media item points to, only available if the url points to a local file
        uploaded within the component message.
    """
    __slots__ = ...
    def __init__(self, url: str) -> None:
        ...
    
    @property
    def flags(self) -> AttachmentFlags:
        """:class:`AttachmentFlags`: This media item's flags."""
        ...
    
    def __repr__(self) -> str:
        ...
    
    def to_dict(self): # -> dict[str, str]:
        ...
    


class MediaGalleryItem:
    """Represents a :class:`MediaGalleryComponent` media item.

    .. versionadded:: 2.6

    Parameters
    ----------
    media: Union[:class:`str`, :class:`discord.File`, :class:`UnfurledMediaItem`]
        The media item data. This can be a string representing a local
        file uploaded as an attachment in the message, which can be accessed
        using the ``attachment://<filename>`` format, or an arbitrary url.
    description: Optional[:class:`str`]
        The description to show within this item. Up to 256 characters. Defaults
        to ``None``.
    spoiler: :class:`bool`
        Whether this item should be flagged as a spoiler.
    """
    __slots__ = ...
    def __init__(self, media: Union[str, File, UnfurledMediaItem], *, description: Optional[str] = ..., spoiler: bool = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @property
    def media(self) -> UnfurledMediaItem:
        """:class:`UnfurledMediaItem`: This item's media data."""
        ...
    
    @media.setter
    def media(self, value: Union[str, File, UnfurledMediaItem]) -> None:
        ...
    
    def to_dict(self) -> MediaGalleryItemPayload:
        ...
    


class MediaGalleryComponent(Component):
    """Represents a Media Gallery component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a media gallery is
        :class:`discord.ui.MediaGallery` not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    items: List[:class:`MediaGalleryItem`]
        The items this gallery has.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: MediaGalleryComponentPayload, state: Optional[ConnectionState]) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.media_gallery]:
        ...
    
    def to_dict(self) -> MediaGalleryComponentPayload:
        ...
    


class FileComponent(Component):
    """Represents a File component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for create a file component is
        :class:`discord.ui.File` not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    media: :class:`UnfurledMediaItem`
        The unfurled attachment contents of the file.
    spoiler: :class:`bool`
        Whether this file is flagged as a spoiler.
    id: Optional[:class:`int`]
        The ID of this component.
    name: Optional[:class:`str`]
        The displayed file name, only available when received from the API.
    size: Optional[:class:`int`]
        The file size in MiB, only available when received from the API.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: FileComponentPayload, state: Optional[ConnectionState]) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.file]:
        ...
    
    def to_dict(self) -> FileComponentPayload:
        ...
    


class SeparatorComponent(Component):
    """Represents a Separator from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a separator is
        :class:`discord.ui.Separator` not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    spacing: :class:`SeparatorSpacing`
        The spacing size of the separator.
    visible: :class:`bool`
        Whether this separator is visible and shows a divider.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: SeparatorComponentPayload) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.separator]:
        ...
    
    def to_dict(self) -> SeparatorComponentPayload:
        ...
    


class Container(Component):
    """Represents a Container from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a container is
        :class:`discord.ui.Container` not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    children: :class:`Component`
        This container's children.
    spoiler: :class:`bool`
        Whether this container is flagged as a spoiler.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: ContainerComponentPayload, state: Optional[ConnectionState]) -> None:
        ...
    
    @property
    def accent_colour(self) -> Optional[Colour]:
        """Optional[:class:`Colour`]: The container's accent colour."""
        ...
    
    accent_color = ...
    @property
    def type(self) -> Literal[ComponentType.container]:
        ...
    
    def to_dict(self) -> ContainerComponentPayload:
        ...
    


class LabelComponent(Component):
    """Represents a label component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a label is
        :class:`discord.ui.Label` not this one.

    .. versionadded:: 2.6

    Attributes
    ----------
    label: :class:`str`
        The label text to display.
    description: Optional[:class:`str`]
        The description text to display below the label, if any.
    component: :class:`Component`
        The component that this label is associated with.
    id: Optional[:class:`int`]
        The ID of this component.
    """
    __slots__ = ...
    __repr_info__ = ...
    def __init__(self, data: LabelComponentPayload, state: Optional[ConnectionState]) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.label]:
        ...
    
    def to_dict(self) -> LabelComponentPayload:
        ...
    


class FileUploadComponent(Component):
    """Represents a file upload component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a file upload is
        :class:`discord.ui.FileUpload` not this one.

    .. versionadded:: 2.7

    Attributes
    ------------
    custom_id: Optional[:class:`str`]
        The ID of the component that gets received during an interaction.
    min_values: :class:`int`
        The minimum number of files that must be uploaded for this component.
        Defaults to 1 and must be between 0 and 10.
    max_values: :class:`int`
        The maximum number of files that must be uploaded for this component.
        Defaults to 1 and must be between 1 and 10.
    id: Optional[:class:`int`]
        The ID of this component.
    required: :class:`bool`
        Whether the component is required.
        Defaults to ``True``.
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: FileUploadComponentPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.file_upload]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> FileUploadComponentPayload:
        ...
    


class RadioGroupComponent(Component):
    """Represents a radio group component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a radio group is
        :class:`discord.ui.RadioGroup` not this one.

    .. versionadded:: 2.7

    Attributes
    ------------
    custom_id: Optional[:class:`str`]
        The ID of the component that gets received during an interaction.
    id: Optional[:class:`int`]
        The ID of this component.
    required: :class:`bool`
        Whether the component is required.
        Defaults to ``True``.
    options: List[:class:`RadioGroupOption`]
        A list of options that can be selected in this group.
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: RadioGroupComponentPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.radio_group]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> RadioGroupComponentPayload:
        ...
    


class RadioGroupOption(BaseOption):
    """Represents a radio group's option

    These can be created by users.

    .. versionadded:: 2.7

    Parameters
    -----------
    label: :class:`str`
        The label of the option. This is displayed to users.
        Can only be up to 100 characters.
    value: :class:`str`
        The value of the option. This is not displayed to users.
        If not provided when constructed then it defaults to the label.
        Can only be up to 100 characters.
    description: Optional[:class:`str`]
        An additional description of the option, if any.
        Can only be up to 100 characters.
    default: :class:`bool`
        Whether this option is selected by default.

    Attributes
    -----------
    label: :class:`str`
        The label of the option. This is displayed to users.
    value: :class:`str`
        The value of the option. This is not displayed to users.
        If not provided when constructed then it defaults to the
        label.
    description: Optional[:class:`str`]
        An additional description of the option, if any.
    default: :class:`bool`
        Whether this option is selected by default.
    """
    ...


class CheckboxGroupComponent(Component):
    """Represents a checkbox group component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a checkbox group is
        :class:`discord.ui.CheckboxGroup` not this one.

    .. versionadded:: 2.7

    Attributes
    ------------
    custom_id: Optional[:class:`str`]
        The ID of the component that gets received during an interaction.
    id: Optional[:class:`int`]
        The ID of this component.
    required: :class:`bool`
        Whether the component is required.
        Defaults to ``True``.
    min_values: :class:`int`
        The minimum number of options that must be selected in this component.
        Must be between 0 and 10. Defaults to 0.
    max_values: :class:`int`
        The maximum number of options that can be selected in this component.
        Must be between 1 and 10. Defaults to 1.
    options: List[:class:`CheckboxGroupOption`]
        A list of options that can be selected in this group.
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: CheckboxGroupComponentPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.checkbox_group]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> CheckboxGroupComponentPayload:
        ...
    


class CheckboxGroupOption(BaseOption):
    """Represents a checkbox group's option

    These can be created by users.

    .. versionadded:: 2.7

    Parameters
    -----------
    label: :class:`str`
        The label of the option. This is displayed to users.
        Can only be up to 100 characters.
    value: :class:`str`
        The value of the option. This is not displayed to users.
        If not provided when constructed then it defaults to the label.
        Can only be up to 100 characters.
    description: Optional[:class:`str`]
        An additional description of the option, if any.
        Can only be up to 100 characters.
    default: :class:`bool`
        Whether this option is selected by default.

    Attributes
    -----------
    label: :class:`str`
        The label of the option. This is displayed to users.
    value: :class:`str`
        The value of the option. This is not displayed to users.
        If not provided when constructed then it defaults to the
        label.
    description: Optional[:class:`str`]
        An additional description of the option, if any.
    default: :class:`bool`
        Whether this option is selected by default.
    """
    ...


class CheckboxComponent(Component):
    """Represents a checkbox component from the Discord Bot UI Kit.

    This inherits from :class:`Component`.

    .. note::

        The user constructible and usable type for creating a checkbox is
        :class:`discord.ui.Checkbox` not this one.

    .. versionadded:: 2.7

    Attributes
    ------------
    custom_id: Optional[:class:`str`]
        The ID of the component that gets received during an interaction.
    id: Optional[:class:`int`]
        The ID of this component.
    default: :class:`bool`
        Whether this checkbox is selected by default.
    """
    __slots__: Tuple[str, ...] = ...
    __repr_info__: ClassVar[Tuple[str, ...]] = ...
    def __init__(self, data: CheckboxComponentPayload, /) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.checkbox]:
        """:class:`ComponentType`: The type of component."""
        ...
    
    def to_dict(self) -> CheckboxComponentPayload:
        ...
    


