"""
This type stub file was generated by pyright.
"""

from typing import Iterable, List, Optional, TYPE_CHECKING, Union
from .mixins import Hashable
from .enums import OnboardingPromptType
from .partial_emoji import PartialEmoji
from .utils import cached_slot_property
from typing_extensions import Self
from .abc import GuildChannel, Snowflake
from .emoji import Emoji
from .guild import Guild
from .role import Role
from .threads import Thread
from .types.onboarding import CreatePromptOption as CreatePromptOptionPayload, Onboarding as OnboardingPayload, Prompt as PromptPayload, PromptOption as PromptOptionPayload
from .state import ConnectionState

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
__all__ = ('Onboarding', 'OnboardingPrompt', 'OnboardingPromptOption')
if TYPE_CHECKING:
    ...
class OnboardingPromptOption(Hashable):
    """Represents a onboarding prompt option.

    This can be manually created for :meth:`Guild.edit_onboarding`.

    .. versionadded:: 2.6

    Parameters
    -----------
    title: :class:`str`
        The title of this prompt option.
    emoji: Union[:class:`Emoji`, :class:`PartialEmoji`, :class:`str`]
        The emoji tied to this option. May be a custom emoji, or a unicode emoji. I
        f this is a string, it will be converted to a :class:`PartialEmoji`.
    description: Optional[:class:`str`]
        The description of this prompt option.
    channels: Iterable[Union[:class:`abc.Snowflake`, :class:`int`]]
        The channels the user will be added to if this option is selected.
    roles: Iterable[Union[:class:`abc.Snowflake`, :class:`int`]]
        The roles the user will be given if this option is selected.

    Attributes
    -----------
    id: :class:`int`
        The ID of this prompt option. If this was manually created then the ID will be ``0``.
    title: :class:`str`
        The title of this prompt option.
    description: Optional[:class:`str`]
        The description of this prompt option.
    emoji: Optional[Union[:class:`Emoji`, :class:`PartialEmoji`]]
        The emoji tied to this option. May be a custom emoji, or a unicode emoji.
    channel_ids: Set[:class:`int`]
        The IDs of the channels the user will be added to if this option is selected.
    role_ids: Set[:class:`int`]
        The IDs of the roles the user will be given if this option is selected.
    """
    __slots__ = ...
    def __init__(self, *, title: str, emoji: Union[Emoji, PartialEmoji, str] = ..., description: Optional[str] = ..., channels: Iterable[Union[Snowflake, int]] = ..., roles: Iterable[Union[Snowflake, int]] = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @classmethod
    def from_dict(cls, *, data: PromptOptionPayload, state: ConnectionState, guild: Guild) -> Self:
        ...
    
    def to_dict(self) -> CreatePromptOptionPayload:
        ...
    
    @property
    def guild(self) -> Guild:
        """:class:`Guild`: The guild this prompt option is related to.

        Raises
        -------
        ValueError
            If the prompt option was created manually.
        """
        ...
    
    @cached_slot_property('_cs_channels')
    def channels(self) -> List[Union[GuildChannel, Thread]]:
        """List[Union[:class:`abc.GuildChannel`, :class:`Thread`]]: The list of channels which will be made visible if this option is selected.

        Raises
        -------
        ValueError
            IF the prompt option is manually created, therefore has no guild.
        """
        ...
    
    @cached_slot_property('_cs_roles')
    def roles(self) -> List[Role]:
        """List[:class:`Role`]: The list of roles given to the user if this option is selected.

        Raises
        -------
        ValueError
            If the prompt option is manually created, therefore has no guild.
        """
        ...
    


class OnboardingPrompt:
    """Represents a onboarding prompt.

    This can be manually created for :meth:`Guild.edit_onboarding`.

    .. versionadded:: 2.6

    Parameters
    -----------
    type: :class:`OnboardingPromptType`
        The type of this prompt.
    title: :class:`str`
        The title of this prompt.
    options: List[:class:`OnboardingPromptOption`]
        The options of this prompt.
    single_select: :class:`bool`
        Whether this prompt is single select.
        Defaults to ``True``.
    required: :class:`bool`
        Whether this prompt is required.
        Defaults to ``True``.
    in_onboarding: :class:`bool`
        Whether this prompt is in the onboarding flow.
        Defaults to ``True``.

    Attributes
    -----------
    id: :class:`int`
        The ID of this prompt. If this was manually created then the ID will be ``0``.
    type: :class:`OnboardingPromptType`
        The type of this prompt.
    title: :class:`str`
        The title of this prompt.
    options: List[:class:`OnboardingPromptOption`]
        The options of this prompt.
    single_select: :class:`bool`
        Whether this prompt is single select.
    required: :class:`bool`
        Whether this prompt is required.
    in_onboarding: :class:`bool`
        Whether this prompt is in the onboarding flow.
    """
    __slots__ = ...
    def __init__(self, *, type: OnboardingPromptType, title: str, options: List[OnboardingPromptOption], single_select: bool = ..., required: bool = ..., in_onboarding: bool = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @classmethod
    def from_dict(cls, *, data: PromptPayload, state: ConnectionState, guild: Guild) -> Self:
        ...
    
    def to_dict(self, *, id: int) -> PromptPayload:
        ...
    
    @property
    def guild(self) -> Guild:
        """:class:`Guild`: The guild this prompt is related to.

        Raises
        ------
        ValueError
            If the prompt was created manually.
        """
        ...
    
    def get_option(self, option_id: int, /) -> Optional[OnboardingPromptOption]:
        """Optional[:class:`OnboardingPromptOption`]: The option with the given ID, if found."""
        ...
    


class Onboarding:
    """Represents a guild's onboarding configuration.

    .. versionadded:: 2.6

    Attributes
    -----------
    guild: :class:`Guild`
        The guild the onboarding configuration is for.
    prompts: List[:class:`OnboardingPrompt`]
        The list of prompts shown during the onboarding and customize community flows.
    default_channel_ids: Set[:class:`int`]
        The IDs of the channels exposed to a new user by default.
    enabled: :class:`bool`:
        Whether onboarding is enabled in this guild.
    mode: :class:`OnboardingMode`
        The mode of onboarding for this guild.
    """
    __slots__ = ...
    def __init__(self, *, data: OnboardingPayload, guild: Guild, state: ConnectionState) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @cached_slot_property('_cs_default_channels')
    def default_channels(self) -> List[Union[GuildChannel, Thread]]:
        """List[Union[:class:`abc.GuildChannel`, :class:`Thread`]]: The list of channels exposed to a new user by default."""
        ...
    
    def get_prompt(self, prompt_id: int, /) -> Optional[OnboardingPrompt]:
        """Optional[:class:`OnboardingPrompt`]: The prompt with the given ID, if found."""
        ...
    


