"""
This type stub file was generated by pyright.
"""

from typing import Iterator, List, Literal, Optional, Tuple
from .state import ConnectionState

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
__all__ = ('SearchAuthorType', 'SearchHas', 'SearchEmbedType', 'SearchResult')
class _BaseSearchType:
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __iter__(self) -> Iterator[str]:
        ...
    


class SearchAuthorType(_BaseSearchType):
    """Represents the search ``author_type`` filter.

    .. versionadded:: 2.7

    Parameters
    ----------
    user: Optional[:class:`bool`]
        Whether to include regular users in the search. This can be ``False`` to exclude instead.
    bot: Optional[:class:`bool`]
        Whether to include bots in the search. This can be ``False`` to exclude instead.
    webhook: Optional[:class:`bool`]
        Whether to include webhooks in the search. This can be ``False`` to exclude instead.
    """
    __slots__ = ...
    def __init__(self, *, user: Optional[bool] = ..., bot: Optional[bool] = ..., webhook: Optional[bool] = ...) -> None:
        ...
    
    @property
    def user(self) -> Optional[bool]:
        """Optional[bool]: Whether regular users are included in the search."""
        ...
    
    @user.setter
    def user(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def bot(self) -> Optional[bool]:
        """Optional[bool]: Whether bots are included in the search."""
        ...
    
    @bot.setter
    def bot(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def webhook(self) -> Optional[bool]:
        """Optional[bool]: Whether webhooks are included in the search."""
        ...
    
    @webhook.setter
    def webhook(self, value: Optional[bool]) -> None:
        ...
    


class SearchHas(_BaseSearchType):
    """Represents the search ``has`` filter.

    .. versionadded:: 2.7

    Parameters
    ----------
    link: Optional[:class:`bool`]
        Whether to include messages with a link. This can be ``False`` to exclude instead.
    embed: Optional[:class:`bool`]
        Whether to include messages with an embed. This can be ``False`` to exclude instead.
    file: Optional[:class:`bool`]
        Whether to include messages with an uploaded file. This can be ``False`` to exclude instead.
    image: Optional[:class:`bool`]
        Whether to include messages with an image. This can be ``False`` to exclude instead.
    video: Optional[:class:`bool`]
        Whether to include messages with a video. This can be ``False`` to exclude instead.
    sound: Optional[:class:`bool`]
        Whether to include messages with an uploaded audio file. This can be ``False`` to exclude instead.
    sticker: Optional[:class:`bool`]
        Whether to include messages with a sticker. This can be ``False`` to exclude instead.
    poll: Optional[:class:`bool`]
        Whether to include messages with a poll. This can be ``False`` to exclude instead.
    snapshot: Optional[:class:`bool`]
        Whether to include messages with a forwarded message. This can be ``False`` to exclude instead.
    """
    def __init__(self, *, link: Optional[bool] = ..., embed: Optional[bool] = ..., file: Optional[bool] = ..., image: Optional[bool] = ..., video: Optional[bool] = ..., sound: Optional[bool] = ..., sticker: Optional[bool] = ..., poll: Optional[bool] = ..., snapshot: Optional[bool] = ...) -> None:
        ...
    
    @property
    def link(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with a link."""
        ...
    
    @link.setter
    def link(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def embed(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with an embed."""
        ...
    
    @embed.setter
    def embed(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def file(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with an uploaded file."""
        ...
    
    @file.setter
    def file(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def image(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with an image."""
        ...
    
    @image.setter
    def image(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def video(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with a video."""
        ...
    
    @video.setter
    def video(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def sound(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with an uploaded audio file."""
        ...
    
    @sound.setter
    def sound(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def sticker(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with a sticker."""
        ...
    
    @sticker.setter
    def sticker(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def poll(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with a poll."""
        ...
    
    @poll.setter
    def poll(self, value: Optional[bool]) -> None:
        ...
    
    @property
    def snapshot(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether to include messages with a forwarded message."""
        ...
    
    @snapshot.setter
    def snapshot(self, value: Optional[bool]) -> None:
        ...
    


class SearchEmbedType(_BaseSearchType):
    """Represents the search ``embed_type`` filter.

    .. versionadded:: 2.7

    Parameters
    ----------
    image: Optional[:class:`bool`]
        Whether to include image embeds. This *cannot* be ``False`` to exclude.
    video: Optional[:class:`bool`]
        Whether to include video embeds. This *cannot* be ``False`` to exclude.
    gif: Optional[:class:`bool`]
        Whether to include gif embeds. This *cannot* be ``False`` to exclude.
    sound: Optional[:class:`bool`]
        Whether to include sound embeds. This *cannot* be ``False`` to exclude.
    article: Optional[:class:`bool`]
        Whether to include article embeds. This *cannot* be ``False`` to exclude.
    """
    def __init__(self, *, image: Literal[True, None] = ..., video: Literal[True, None] = ..., gif: Literal[True, None] = ..., sound: Literal[True, None] = ..., article: Literal[True, None] = ...) -> None:
        ...
    
    @property
    def image(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether image embeds are included in the search."""
        ...
    
    @image.setter
    def image(self, value: Literal[True, None]) -> None:
        ...
    
    @property
    def video(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether video embeds are included in the search."""
        ...
    
    @video.setter
    def video(self, value: Literal[True, None]) -> None:
        ...
    
    @property
    def gif(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether gif embeds are included in the search."""
        ...
    
    @gif.setter
    def gif(self, value: Literal[True, None]) -> None:
        ...
    
    @property
    def sound(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether sound embeds are included in the search."""
        ...
    
    @sound.setter
    def sound(self, value: Literal[True, None]) -> None:
        ...
    
    @property
    def article(self) -> Optional[bool]:
        """Optional[:class:`bool`]: Whether article embeds are included in the search."""
        ...
    
    @article.setter
    def article(self, value: Literal[True, None]) -> None:
        ...
    


class _SearchResultFuture:
    def __init__(self, *, state: ConnectionState, params: List[Tuple[str, str]], limit: Optional[int], wait_for_index: bool) -> None:
        ...
    


