"""
This type stub file was generated by pyright.
"""

import datetime
from typing import Optional, TYPE_CHECKING
from .mixins import Hashable
from .state import ConnectionState
from .types.subscription import Subscription as SubscriptionPayload
from .user import User

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
__all__ = ('Subscription', )
class Subscription(Hashable):
    """Represents a Discord subscription.

    .. versionadded:: 2.5

    Attributes
    -----------
    id: :class:`int`
        The subscription's ID.
    user_id: :class:`int`
        The ID of the user that is subscribed.
    sku_ids: List[:class:`int`]
        The IDs of the SKUs that the user subscribed to.
    entitlement_ids: List[:class:`int`]
        The IDs of the entitlements granted for this subscription.
    current_period_start: :class:`datetime.datetime`
        When the current billing period started.
    current_period_end: :class:`datetime.datetime`
        When the current billing period ends.
    status: :class:`SubscriptionStatus`
        The status of the subscription.
    canceled_at: Optional[:class:`datetime.datetime`]
        When the subscription was canceled.
        This is only available for subscriptions with a :attr:`status` of :attr:`SubscriptionStatus.inactive`.
    renewal_sku_ids: List[:class:`int`]
        The IDs of the SKUs that the user is going to be subscribed to when renewing.
    """
    __slots__ = ...
    def __init__(self, *, state: ConnectionState, data: SubscriptionPayload) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @property
    def created_at(self) -> datetime.datetime:
        """:class:`datetime.datetime`: Returns the subscription's creation time in UTC."""
        ...
    
    @property
    def user(self) -> Optional[User]:
        """Optional[:class:`User`]: The user that is subscribed."""
        ...
    


