"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional, TYPE_CHECKING, Tuple, TypeVar
from ..components import CheckboxComponent, CheckboxGroupComponent, CheckboxGroupOption
from ..enums import ComponentType
from .item import Item
from typing_extensions import Self
from ..types.components import CheckboxComponent as CheckboxComponentPayload, CheckboxGroupComponent as CheckboxGroupComponentPayload
from .view import BaseView

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
__all__ = ('CheckboxGroup', 'Checkbox')
V = TypeVar('V', bound='BaseView', covariant=True)
class CheckboxGroup(Item[V]):
    """Represents a checkbox group component within a modal.

    .. versionadded:: 2.7

    Parameters
    ------------
    id: Optional[:class:`int`]
        The ID of the component. This must be unique across the view.
    custom_id: Optional[:class:`str`]
        The custom ID of the component.
    options: List[:class:`discord.CheckboxGroupOption`]
        A list of options that can be selected in this checkbox group.
        Can only contain up to 10 items.
    max_values: Optional[:class:`int`]
        The maximum number of options that can be selected in this component.
        Must be between 1 and 10. Defaults to 1.
    min_values: Optional[:class:`int`]
        The minimum number of options that must be selected in this component.
        Must be between 0 and 10. Defaults to 0.
    required: :class:`bool`
        Whether this component is required to be filled before submitting the modal.
        Defaults to ``True``.
    """
    __item_repr_attributes__: Tuple[str, ...] = ...
    def __init__(self, *, custom_id: str = ..., required: bool = ..., min_values: Optional[int] = ..., max_values: Optional[int] = ..., options: List[CheckboxGroupOption] = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def id(self) -> Optional[int]:
        """Optional[:class:`int`]: The ID of this component."""
        ...
    
    @id.setter
    def id(self, value: Optional[int]) -> None:
        ...
    
    @property
    def values(self) -> List[str]:
        """List[:class:`str`]: A list of values that have been selected by the user."""
        ...
    
    @property
    def custom_id(self) -> str:
        """:class:`str`: The ID of the component that gets received during an interaction."""
        ...
    
    @custom_id.setter
    def custom_id(self, value: str) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.checkbox_group]:
        """:class:`.ComponentType`: The type of this component."""
        ...
    
    @property
    def options(self) -> List[CheckboxGroupOption]:
        """List[:class:`discord.CheckboxGroupOption`]: A list of options that can be selected in this menu."""
        ...
    
    @options.setter
    def options(self, value: List[CheckboxGroupOption]) -> None:
        ...
    
    @property
    def min_values(self) -> int:
        """:class:`int`: The minimum number of options that must be selected before submitting the modal."""
        ...
    
    @min_values.setter
    def min_values(self, value: int) -> None:
        ...
    
    @property
    def max_values(self) -> int:
        """:class:`int`: The maximum number of options that can be selected before submitting the modal."""
        ...
    
    @max_values.setter
    def max_values(self, value: int) -> None:
        ...
    
    def add_option(self, *, label: str, value: str = ..., description: Optional[str] = ..., default: bool = ...) -> None:
        """Adds an option to the checkbox group.

        To append a pre-existing :class:`discord.CheckboxGroupOption` use the
        :meth:`append_option` method instead.

        Parameters
        -----------
        label: :class:`str`
            The label of the option. This is displayed to users.
            Can only be up to 100 characters.
        value: :class:`str`
            The value of the option. This is not displayed to users.
            If not given, defaults to the label.
            Can only be up to 100 characters.
        description: Optional[:class:`str`]
            An additional description of the option, if any.
            Can only be up to 100 characters.
        default: :class:`bool`
            Whether this option is selected by default.

        Raises
        -------
        ValueError
            The number of options exceeds 10.
        """
        ...
    
    def append_option(self, option: CheckboxGroupOption) -> None:
        """Appends an option to the checkbox group.

        Parameters
        -----------
        option: :class:`discord.CheckboxGroupOption`
            The option to append to the checkbox group.

        Raises
        -------
        ValueError
            The number of options exceeds 10.
        """
        ...
    
    @property
    def required(self) -> bool:
        """:class:`bool`: Whether the component is required or not."""
        ...
    
    @required.setter
    def required(self, value: bool) -> None:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    def to_component_dict(self) -> CheckboxGroupComponentPayload:
        ...
    
    @classmethod
    def from_component(cls, component: CheckboxGroupComponent) -> Self:
        ...
    
    def is_dispatchable(self) -> bool:
        ...
    


class Checkbox(Item[V]):
    """Represents a checkbox component within a modal.

    .. versionadded:: 2.7

    Parameters
    ------------
    id: Optional[:class:`int`]
        The ID of the component. This must be unique across the view.
    custom_id: Optional[:class:`str`]
        The custom ID of the component.
    default: :class:`bool`
        Whether this checkbox is selected by default.
    """
    __item_repr_attributes__: Tuple[str, ...] = ...
    def __init__(self, *, custom_id: str = ..., default: bool = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def id(self) -> Optional[int]:
        """Optional[:class:`int`]: The ID of this component."""
        ...
    
    @id.setter
    def id(self, value: Optional[int]) -> None:
        ...
    
    @property
    def value(self) -> bool:
        """:class:`bool`: ``True`` if this checkbox was selected, otherwise ``False``."""
        ...
    
    @property
    def custom_id(self) -> str:
        """:class:`str`: The ID of the component that gets received during an interaction."""
        ...
    
    @custom_id.setter
    def custom_id(self, value: str) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.checkbox]:
        """:class:`.ComponentType`: The type of this component."""
        ...
    
    @property
    def default(self) -> bool:
        """:class:`bool`: Whether this checkbox is selected by default."""
        ...
    
    @default.setter
    def default(self, value: bool) -> None:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    def to_component_dict(self) -> CheckboxComponentPayload:
        ...
    
    @classmethod
    def from_component(cls, component: CheckboxComponent) -> Self:
        ...
    
    def is_dispatchable(self) -> bool:
        ...
    


