"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional, TYPE_CHECKING, Tuple, TypeVar
from ..components import FileUploadComponent
from ..enums import ComponentType
from .item import Item
from typing_extensions import Self
from ..message import Attachment
from ..types.components import FileUploadComponent as FileUploadComponentPayload
from .view import BaseView

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
__all__ = ('FileUpload', )
V = TypeVar('V', bound='BaseView', covariant=True)
class FileUpload(Item[V]):
    """Represents a file upload component within a modal.

    .. versionadded:: 2.7

    Parameters
    ------------
    id: Optional[:class:`int`]
        The ID of the component. This must be unique across the view.
    custom_id: Optional[:class:`str`]
        The custom ID of the file upload component.
    max_values: Optional[:class:`int`]
        The maximum number of files that can be uploaded in this component.
        Must be between 1 and 10. Defaults to 1.
    min_values: Optional[:class:`int`]
        The minimum number of files that must be uploaded in this component.
        Must be between 0 and 10. Defaults to 0.
    required: :class:`bool`
        Whether this component is required to be filled before submitting the modal.
        Defaults to ``True``.
    """
    __item_repr_attributes__: Tuple[str, ...] = ...
    def __init__(self, *, custom_id: str = ..., required: bool = ..., min_values: Optional[int] = ..., max_values: Optional[int] = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def id(self) -> Optional[int]:
        """Optional[:class:`int`]: The ID of this component."""
        ...
    
    @id.setter
    def id(self, value: Optional[int]) -> None:
        ...
    
    @property
    def values(self) -> List[Attachment]:
        """List[:class:`discord.Attachment`]: The list of attachments uploaded by the user.

        You can call :meth:`~discord.Attachment.to_file` on each attachment
        to get a :class:`~discord.File` for sending.
        """
        ...
    
    @property
    def custom_id(self) -> str:
        """:class:`str`: The ID of the component that gets received during an interaction."""
        ...
    
    @custom_id.setter
    def custom_id(self, value: str) -> None:
        ...
    
    @property
    def min_values(self) -> int:
        """:class:`int`: The minimum number of files that must be user upload before submitting the modal."""
        ...
    
    @min_values.setter
    def min_values(self, value: int) -> None:
        ...
    
    @property
    def max_values(self) -> int:
        """:class:`int`: The maximum number of files that the user must upload before submitting the modal."""
        ...
    
    @max_values.setter
    def max_values(self, value: int) -> None:
        ...
    
    @property
    def required(self) -> bool:
        """:class:`bool`: Whether the component is required or not."""
        ...
    
    @required.setter
    def required(self, value: bool) -> None:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    def to_component_dict(self) -> FileUploadComponentPayload:
        ...
    
    @classmethod
    def from_component(cls, component: FileUploadComponent) -> Self:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.file_upload]:
        ...
    
    def is_dispatchable(self) -> bool:
        ...
    


