"""
This type stub file was generated by pyright.
"""

from typing import Generator, Literal, Optional, TYPE_CHECKING, Tuple, TypeVar
from ..components import LabelComponent
from ..enums import ComponentType
from .item import Item
from typing_extensions import Self
from ..types.components import LabelComponent as LabelComponentPayload
from .view import BaseView

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
__all__ = ('Label', )
V = TypeVar('V', bound='BaseView', covariant=True)
class Label(Item[V]):
    """Represents a UI label within a modal.

    This is a top-level layout component that can only be used on :class:`Modal`.

    .. versionadded:: 2.6

    Parameters
    ------------
    text: :class:`str`
        The text to display above the input field.
        Can only be up to 45 characters.
    description: Optional[:class:`str`]
        The description text to display right below the label text.
        Can only be up to 100 characters.
    component: :class:`Item`
        The component to display below the label.
    id: Optional[:class:`int`]
        The ID of the component. This must be unique across the view.

    Attributes
    ------------
    text: :class:`str`
        The text to display above the input field.
        Can only be up to 45 characters.
    description: Optional[:class:`str`]
        The description text to display right below the label text.
        Can only be up to 100 characters.
    component: :class:`Item`
        The component to display below the label.
    """
    __item_repr_attributes__: Tuple[str, ...] = ...
    def __init__(self, *, text: str, component: Item[V], description: Optional[str] = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    def walk_children(self) -> Generator[Item[V], None, None]:
        ...
    
    def to_component_dict(self) -> LabelComponentPayload:
        ...
    
    @classmethod
    def from_component(cls, component: LabelComponent) -> Self:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.label]:
        ...
    
    def is_dispatchable(self) -> bool:
        ...
    


