"""
This type stub file was generated by pyright.
"""

from typing import List, Literal, Optional, TYPE_CHECKING, Tuple, TypeVar
from ..components import RadioGroupComponent, RadioGroupOption
from ..enums import ComponentType
from .item import Item
from typing_extensions import Self
from ..types.components import RadioGroupComponent as RadioGroupComponentPayload
from .view import BaseView

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
__all__ = ('RadioGroup', )
V = TypeVar('V', bound='BaseView', covariant=True)
class RadioGroup(Item[V]):
    """Represents a radio group component within a modal.

    .. versionadded:: 2.7

    Parameters
    ------------
    id: Optional[:class:`int`]
        The ID of the component. This must be unique across the view.
    custom_id: Optional[:class:`str`]
        The custom ID of the component.
    options: List[:class:`discord.RadioGroupOption`]
        A list of options that can be selected in this radio group.
        Can contain between 2 and 10 items.
    required: :class:`bool`
        Whether this component is required to be filled before submitting the modal.
        Defaults to ``True``.
    """
    __item_repr_attributes__: Tuple[str, ...] = ...
    def __init__(self, *, custom_id: str = ..., required: bool = ..., options: List[RadioGroupOption] = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def id(self) -> Optional[int]:
        """Optional[:class:`int`]: The ID of this component."""
        ...
    
    @id.setter
    def id(self, value: Optional[int]) -> None:
        ...
    
    @property
    def value(self) -> Optional[str]:
        """Optional[:class:`str`]: The value have been selected by the user, if any."""
        ...
    
    @property
    def custom_id(self) -> str:
        """:class:`str`: The ID of the component that gets received during an interaction."""
        ...
    
    @custom_id.setter
    def custom_id(self, value: str) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.radio_group]:
        """:class:`.ComponentType`: The type of this component."""
        ...
    
    @property
    def options(self) -> List[RadioGroupOption]:
        """List[:class:`discord.RadioGroupOption`]: A list of options that can be selected in this radio group."""
        ...
    
    @options.setter
    def options(self, value: List[RadioGroupOption]) -> None:
        ...
    
    def add_option(self, *, label: str, value: str = ..., description: Optional[str] = ..., default: bool = ...) -> None:
        """Adds an option to the group.

        To append a pre-existing :class:`discord.RadioGroupOption` use the
        :meth:`append_option` method instead.

        Parameters
        -----------
        label: :class:`str`
            The label of the option. This is displayed to users.
            Can only be up to 100 characters.
        value: :class:`str`
            The value of the option. This is not displayed to users.
            If not given, defaults to the label.
            Can only be up to 100 characters.
        description: Optional[:class:`str`]
            An additional description of the option, if any.
            Can only be up to 100 characters.
        default: :class:`bool`
            Whether this option is selected by default.

        Raises
        -------
        ValueError
            The number of options exceeds 10.
        """
        ...
    
    def append_option(self, option: RadioGroupOption) -> None:
        """Appends an option to the group.

        Parameters
        -----------
        option: :class:`discord.RadioGroupOption`
            The option to append to the group.

        Raises
        -------
        ValueError
            The number of options exceeds 10.
        """
        ...
    
    @property
    def required(self) -> bool:
        """:class:`bool`: Whether the component is required or not."""
        ...
    
    @required.setter
    def required(self, value: bool) -> None:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    def to_component_dict(self) -> RadioGroupComponentPayload:
        ...
    
    @classmethod
    def from_component(cls, component: RadioGroupComponent) -> Self:
        ...
    
    def is_dispatchable(self) -> bool:
        ...
    


