"""
This type stub file was generated by pyright.
"""

from typing import Any, ClassVar, Dict, Generator, List, Literal, Optional, TYPE_CHECKING, TypeVar, Union
from .item import Item
from ..enums import ComponentType
from typing_extensions import Self
from .view import LayoutView
from ..components import SectionComponent

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
V = TypeVar('V', bound='LayoutView', covariant=True)
__all__ = ('Section', )
class Section(Item[V]):
    r"""Represents a UI section.

    This is a top-level layout component that can only be used on :class:`LayoutView`.

    .. versionadded:: 2.6

    Parameters
    ----------
    \*children: Union[:class:`str`, :class:`TextDisplay`]
        The text displays of this section. Up to 3.
    accessory: :class:`Item`
        The section accessory. This is usually either a :class:`Button` or :class:`Thumbnail`.
    id: Optional[:class:`int`]
        The ID of this component. This must be unique across the view.
    """
    __item_repr_attributes__ = ...
    __discord_ui_section__: ClassVar[bool] = ...
    __slots__ = ...
    def __init__(self, *children: Union[Item[V], str], accessory: Item[V], id: Optional[int] = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.section]:
        ...
    
    @property
    def children(self) -> List[Item[V]]:
        """List[:class:`Item`]: The list of children attached to this section."""
        ...
    
    @property
    def width(self): # -> Literal[5]:
        ...
    
    @property
    def accessory(self) -> Item[V]:
        """:class:`Item`: The section's accessory."""
        ...
    
    @accessory.setter
    def accessory(self, value: Item[V]) -> None:
        ...
    
    def walk_children(self) -> Generator[Item[V], None, None]:
        """An iterator that recursively walks through all the children of this section
        and its children, if applicable. This includes the `accessory`.

        Yields
        ------
        :class:`Item`
            An item in this section.
        """
        ...
    
    def content_length(self) -> int:
        """:class:`int`: Returns the total length of all text content in this section."""
        ...
    
    def add_item(self, item: Union[str, Item[Any]]) -> Self:
        """Adds an item to this section.

        This function returns the class instance to allow for fluent-style
        chaining.

        Parameters
        ----------
        item: Union[:class:`str`, :class:`Item`]
            The item to append, if it is a string it automatically wrapped around
            :class:`TextDisplay`.

        Raises
        ------
        TypeError
            An :class:`Item` or :class:`str` was not passed.
        ValueError
            Maximum number of children has been exceeded (3) or (40)
            for the entire view.
        """
        ...
    
    def remove_item(self, item: Item[Any]) -> Self:
        """Removes an item from this section.

        This function returns the class instance to allow for fluent-style
        chaining.

        Parameters
        ----------
        item: :class:`Item`
            The item to remove from the section.
        """
        ...
    
    def find_item(self, id: int, /) -> Optional[Item[V]]:
        """Gets an item with :attr:`Item.id` set as ``id``, or ``None`` if
        not found.

        .. warning::

            This is **not the same** as ``custom_id``.

        Parameters
        ----------
        id: :class:`int`
            The ID of the component.

        Returns
        -------
        Optional[:class:`Item`]
            The item found, or ``None``.
        """
        ...
    
    def clear_items(self) -> Self:
        """Removes all the items from the section.

        This function returns the class instance to allow for fluent-style
        chaining.
        """
        ...
    
    @classmethod
    def from_component(cls, component: SectionComponent) -> Self:
        ...
    
    def to_components(self) -> List[Dict[str, Any]]:
        ...
    
    def to_component_dict(self) -> Dict[str, Any]:
        ...
    


