"""
This type stub file was generated by pyright.
"""

from typing import Literal, Optional, TYPE_CHECKING, TypeVar
from .item import Item
from ..components import SeparatorComponent
from ..enums import ComponentType, SeparatorSpacing
from typing_extensions import Self
from .view import LayoutView

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
V = TypeVar('V', bound='LayoutView', covariant=True)
__all__ = ('Separator', )
class Separator(Item[V]):
    """Represents a UI separator.

    This is a top-level layout component that can only be used on :class:`LayoutView`.

    .. versionadded:: 2.6

    Parameters
    ----------
    visible: :class:`bool`
        Whether this separator is visible. On the client side this
        is whether a divider line should be shown or not.
    spacing: :class:`.SeparatorSpacing`
        The spacing of this separator.
    id: Optional[:class:`int`]
        The ID of this component. This must be unique across the view.
    """
    __slots__ = ...
    __item_repr_attributes__ = ...
    def __init__(self, *, visible: bool = ..., spacing: SeparatorSpacing = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def id(self) -> Optional[int]:
        """Optional[:class:`int`]: The ID of this separator."""
        ...
    
    @id.setter
    def id(self, value: Optional[int]) -> None:
        ...
    
    @property
    def visible(self) -> bool:
        """:class:`bool`: Whether this separator is visible.

        On the client side this is whether a divider line should
        be shown or not.
        """
        ...
    
    @visible.setter
    def visible(self, value: bool) -> None:
        ...
    
    @property
    def spacing(self) -> SeparatorSpacing:
        """:class:`.SeparatorSpacing`: The spacing of this separator."""
        ...
    
    @spacing.setter
    def spacing(self, value: SeparatorSpacing) -> None:
        ...
    
    @property
    def width(self): # -> Literal[5]:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.separator]:
        ...
    
    def to_component_dict(self): # -> SeparatorComponent:
        ...
    
    @classmethod
    def from_component(cls, component: SeparatorComponent) -> Self:
        ...
    


