"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Literal, Optional, TYPE_CHECKING, TypeVar, Union
from .item import Item
from ..enums import ComponentType
from ..components import ThumbnailComponent, UnfurledMediaItem
from ..file import File
from typing_extensions import Self
from .view import LayoutView

"""
The MIT License (MIT)

Copyright (c) 2015-present Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
if TYPE_CHECKING:
    ...
V = TypeVar('V', bound='LayoutView', covariant=True)
__all__ = ('Thumbnail', )
class Thumbnail(Item[V]):
    """Represents a UI Thumbnail. This currently can only be used as a :class:`Section`\'s accessory.

    .. versionadded:: 2.6

    Parameters
    ----------
    media: Union[:class:`str`, :class:`discord.File`, :class:`discord.UnfurledMediaItem`]
        The media of the thumbnail. This can be a URL or a reference
        to an attachment that matches the ``attachment://filename.extension``
        structure.
    description: Optional[:class:`str`]
        The description of this thumbnail. Up to 256 characters. Defaults to ``None``.
    spoiler: :class:`bool`
        Whether to flag this thumbnail as a spoiler. Defaults to ``False``.
    id: Optional[:class:`int`]
        The ID of this component. This must be unique across the view.
    """
    __slots__ = ...
    __item_repr_attributes__ = ...
    def __init__(self, media: Union[str, File, UnfurledMediaItem], *, description: Optional[str] = ..., spoiler: bool = ..., id: Optional[int] = ...) -> None:
        ...
    
    @property
    def width(self): # -> Literal[5]:
        ...
    
    @property
    def media(self) -> UnfurledMediaItem:
        """:class:`discord.UnfurledMediaItem`: This thumbnail unfurled media data."""
        ...
    
    @media.setter
    def media(self, value: Union[str, File, UnfurledMediaItem]) -> None:
        ...
    
    @property
    def type(self) -> Literal[ComponentType.thumbnail]:
        ...
    
    def to_component_dict(self) -> Dict[str, Any]:
        ...
    
    @classmethod
    def from_component(cls, component: ThumbnailComponent) -> Self:
        ...
    


