"""Generate peninsular-Spanish audio for the LLM example sentences (vocab + conjugation decks).

The vocab / conjugation cards each carry a Spanish example sentence (``example_sentence_es``),
generated by the LLM-enrichment step. This script synthesizes one audio clip per **unique**
sentence into ``anki/sentence_audio/`` using the same offline TTS as the Numbers deck
(``tts.py``). ``make_anki_deck.py`` then bundles the clips referenced by each deck into that
deck's ``.apkg`` and auto-plays them Duolingo-style (on the side that shows the Spanish sentence).

Same design as ``generate_number_audio.py``:
- **Idempotent** — clips already present are skipped (content-hash filenames), so re-running does
  nothing and a partial run just fills in the rest.
- **Backend/voice** chosen via env vars (see ``tts.py``); default is Piper on CPU. For the H100
  route use ``slurm/generate_sentence_audio.slurm`` (``TTS_BACKEND=xtts``).
- **Standalone** — imports only ``tts`` (no genanki), so it runs on the cluster with just the
  ``tts`` extra installed.

The card JSON is gitignored (it lives on your laptop), so **rsync ``anki/`` up to the cluster
first**, run this there, then rsync ``anki/sentence_audio/`` back down.

Run from the repo root (top-level import style):  ``python src/generate_sentence_audio.py``
"""

from __future__ import annotations  # Python 3.9 (some HPC clusters) — keep annotations lazy

import argparse
import json
import os

from spoken_sentence import spoken_sentence
from tts import find_audio, synthesize

# Must match make_anki_deck.py: same env var + default so both agree on which vocab folder to use.
VOCAB_SOURCE = os.getenv("VOCAB_SOURCE", "Refold ES1K")
ANKI_DIR = os.path.join(os.path.dirname(__file__), "../anki")

# Folders whose cards carry a Spanish example sentence. Numbers are handled by
# generate_number_audio.py (they voice the number word, not the example), so they're not here.
SENTENCE_FOLDERS = [
    os.path.join(ANKI_DIR, VOCAB_SOURCE),
    os.path.join(ANKI_DIR, "irregular_verbs"),
    os.path.join(ANKI_DIR, "regular_verbs"),
]

# The single card field that holds the spoken Spanish sentence (shared by vocab + conjugation).
SENTENCE_FIELD = "example_sentence_es"

# One shared, content-hash-keyed pool for all sentence audio; make_anki_deck.py reads the same dir.
MEDIA_FOLDER = os.path.join(ANKI_DIR, "sentence_audio")


def collect_sentences() -> list[str]:
    """Return the sorted set of unique, non-empty Spanish example sentences across all cards."""
    sentences: set[str] = set()
    for folder in SENTENCE_FOLDERS:
        if not os.path.isdir(folder):
            continue
        for name in os.listdir(folder):
            if not name.endswith(".json"):
                continue
            with open(os.path.join(folder, name), encoding="utf-8") as f:
                try:
                    data = json.load(f)
                except json.JSONDecodeError as e:
                    print(f"  skipping {name}: {e}")
                    continue
            for card in data:
                # Forward conjugation cards blank the verb as [infinitive]; spoken_sentence
                # substitutes conjugated_form back so TTS speaks the real conjugated sentence.
                sentence = spoken_sentence(card)
                if sentence:
                    sentences.add(sentence)
    return sorted(sentences)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        metavar="N",
        help="Only synthesize the first N sentences — for a quick smoke test. Idempotent, so a "
        "later full run just fills in the rest.",
    )
    args = parser.parse_args()

    os.makedirs(MEDIA_FOLDER, exist_ok=True)
    sentences = collect_sentences()
    if not sentences:
        print(
            f"No '{SENTENCE_FIELD}' sentences found in {SENTENCE_FOLDERS}.\n"
            "Did you rsync the anki/ card JSON up to the cluster? (It is gitignored.)"
        )
        return
    if args.limit is not None:
        sentences = sentences[: args.limit]
        print(f"SMOKE TEST: limiting to {len(sentences)} sentences")

    generated = skipped = 0
    by_voice: dict[str, int] = {}
    for text in sentences:
        if find_audio(MEDIA_FOLDER, text):
            skipped += 1
            continue
        basename, voice = synthesize(text, MEDIA_FOLDER)
        generated += 1
        # Log the speaker/voice per clip so a degenerate output can be traced back to its voice.
        print(f"  [{voice}]  {text}  ->  {basename}")
        by_voice[voice or "?"] = by_voice.get(voice or "?", 0) + 1

    print(
        f"\nDone: {generated} generated, {skipped} already present "
        f"({len(sentences)} sentences requested) in {MEDIA_FOLDER}"
    )
    if by_voice:
        print("Clips per voice:")
        for voice, count in sorted(by_voice.items()):
            print(f"  {count:>4}  {voice}")


if __name__ == "__main__":
    main()
